server:
  port: 8080
  servlet:
    context-path: /roomreservationapi/v1
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"
spring:
  application:
    name: assignment-hotel-reservation
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hotel-reservation-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "com.example.hotelreservation.event.model"
#        spring.json.value.default.type: "com.example.hotelreservation.event.model.BankTransferPaymentEvent"
#        spring.json.use.type.headers: false

credit-card-payment-api:
#  base-url: http://localhost:9090/host/credit-card-payment-api
  base-url: https://eefcd287-c5b1-416b-9323-632244c15778.mock.pstmn.io/host/credit-card-payment-api  #update this with mock server url from postman - or write wiremock standalone or real implementation

#Runs daily at midnight - checks for auto cancellation of reservation
reservation:
  cancellation:
    deadlineDays: 2
    cron: "0 0 0 * * *"
